---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured for each port
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}/redis_{{ item }}.conf"
    mode: "{{ redis_conf_mode }}"
  with_items: "{{ redis_port }}"
  notify: restart redis

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: Copies init script for each port
  template:
    src: redis.init.j2
    dest: "{{ redis_init_path }}/redis_{{ item }}"
    mode: "{{ redis_init_mode }}"
  with_items: "{{ redis_port }}"
  notify: restart redis

- name: Ensure Redis is running and enabled on boot.
  service:
    name: "redis_{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ redis_port }}"

- name: Removes default conf file
  file:
    path: "{{ redis_conf_path }}/redis.conf"
    state: absent

- name: Removes default init file
  file:
    path: "{{ redis_init_path }}/redis-server"
    state: absent
